# -------------------------------------------------------------------------------------------------
# Copyright (c) 2022, DHS.
#
# This file is part of MicroHapDB (http://github.com/bioforensics/MicroHapDB) and is licensed under
# the BSD license: see LICENSE.txt.
#
# This software was prepared for the Department of Homeland Security (DHS) by the Battelle National
# Biodefense Institute, LLC (BNBI) as part of contract HSHQDC-15-C-00064 to manage and operate the
# National Biodefense Analysis and Countermeasures Center (NBACC), a Federally Funded Research and
# Development Center.
# -------------------------------------------------------------------------------------------------

from util import reformat_markers, reformat_frequencies


rule all:
    input:
        "marker.csv",
        "frequency.csv",


rule markers:
    input:
        txt="original/414_2021_2509_MOESM1_ESM.txt",
    output:
        csv="marker.csv",
        mapfile="idmap.csv",
    run:
        reformat_markers(input.txt, output.csv, output.mapfile)


rule frequencies:
    input:
        freqs="original/414_2021_2509_MOESM2_ESM.txt",
        mapfile="idmap.csv",
    output:
        csv="frequency.csv",
    run:
        reformat_frequencies(input.freqs, input.mapfile, output.csv)
