language: python
branches:
  only:  # don't build "pushes" except on the master branch
    - master
cache: pip
python:
    - 3.6
    - 3.7
install:
    - make devdeps
    - pip install .
script:
    - make test
    - make style
