import pandas as pd


def chrom_from_marker_name(name):
    num = name[2:4]
    if num.startswith("0"):
        num = num[1:]
    return f"chr{num}"


rule markers:
    input:
        txt="Yu2022-TableS1.tsv",
    output:
        csv="marker.csv",
    run:
        markers = pd.read_csv(input.txt, sep="\t")
        markers = markers.rename(columns={"Microhaplotype ID": "Name", "rs_ID": "VarRef"})
        markers["NumVars"] = markers["VarRef"].apply(lambda x: x.count(";") + 1)
        markers["NumVarsPos"] = markers["Position"].apply(lambda x: x.count(";") + 1)
        markers["Consistent"] = markers["NumVars"] == markers["NumVarsPos"]
        inconsistent = markers[markers.Consistent == False]
        assert len(inconsistent) == 0
        markers["Xref"] = None
        markers["Refr"] = None
        markers["Positions"] = None
        substitutions = {
            "21:20110:5": "mh21WL-005",
            "21:13143:4": "mh21WL-002",
            "ss1388052709;ss1388052710;ss1388052713;ss1388052719": "rs6488668;rs7961959;rs10845939;rs118010816",
            "mh06WL-066": "mh06WL-066a",
            "mh06WL-067": "mh06WL-067a",
            "mh06WL-068": "mh06WL-068a",
        }
        markers = markers.replace(substitutions)
        markers.loc[(markers.Name == "mh06WL-069") & (markers.VarRef.str.contains("rs281863504")), "Name"] = "mh06WL-037"
        markers.loc[(markers.Name == "mh22WL-016") & (markers.VarRef.str.contains("rs79222659")), "Name"] = "mh22WL-016a"
        markers.loc[(markers.Name == "mh22WL-016") & (markers.VarRef.str.contains("rs1004689")), "Name"] = "mh22WL-016b"
        markers["Chrom"] = markers["Name"].apply(chrom_from_marker_name)
        markers = markers[["Name", "Xref", "NumVars", "Refr", "Chrom", "Positions", "VarRef"]]
        markers.to_csv(output.csv, index=False)
