# -------------------------------------------------------------------------------------------------
# Copyright (c) 2019, DHS.
#
# This file is part of MicroHapDB (http://github.com/bioforensics/MicroHapDB) and is licensed under
# the BSD license: see LICENSE.txt.
#
# This software was prepared for the Department of Homeland Security (DHS) by the Battelle National
# Biodefense Institute, LLC (BNBI) as part of contract HSHQDC-15-C-00064 to manage and operate the
# National Biodefense Analysis and Countermeasures Center (NBACC), a Federally Funded Research and
# Development Center.
# -------------------------------------------------------------------------------------------------

from util import reformat_markers, reformat_frequencies


rule all:
    input:
        "marker.csv",
        "frequency.csv",


rule markers:
    input:
        tsv="prelim-marker-variants.tsv",
    output:
        csv="marker.csv",
    run:
        reformat_markers(input.tsv, output.csv)


rule frequencies:
    input:
        tsv="prelim-allele-freqs.tsv",
    output:
        csv="frequency.csv",
    run:
        reformat_frequencies(input.tsv, output.csv)
