from microhapdb import markers
from microhapdb.nomenclature import Identifier


rule markers:
    input:
        rsids="notes.csv",
    output:
        marker="marker.csv",
    run:
        with open(input.rsids, "r") as infh, open(output.marker, "w") as outfh:
            print("Name,Xref,NumVars,Refr,Chrom,Positions,VarRef", file=outfh)
            for line in infh:
                name, rsids = line.strip().split(",")
                numvars = rsids.count(";") + 1
                chrom = Identifier(name).chrom
                print(f"{name},,{numvars},,{chrom},,{rsids}", file=outfh)
