# -------------------------------------------------------------------------------------------------
# Copyright (c) 2020, DHS.
#
# This file is part of MicroHapDB (http://github.com/bioforensics/MicroHapDB) and is licensed under
# the BSD license: see LICENSE.txt.
#
# This software was prepared for the Department of Homeland Security (DHS) by the Battelle National
# Biodefense Institute, LLC (BNBI) as part of contract HSHQDC-15-C-00064 to manage and operate the
# National Biodefense Analysis and Countermeasures Center (NBACC), a Federally Funded Research and
# Development Center.
# -------------------------------------------------------------------------------------------------

from util import compile_marker_definitions


rule all:
    input:
        table="table1-subset.tsv",
    output:
        csv="marker.csv",
    run:
        dbsnp38 = config["dbsnp38"]
        rsidx38 = config["dbsnp38"].replace(".vcf.gz", ".rsidx")
        dir1kgp = config["1kgp_dir"]
        compile_marker_definitions(dbsnp38, rsidx38, dir1kgp, input.table)
