import pandas as pd

def chrom_from_marker_name(name):
    num = name[2:4]
    if num.startswith("0"):
        num = num[1:]
    return f"chr{num}"

rule markers:
    input:
        txt="Yu2022-TableS3.tsv"
    output:
        csv="marker.csv"
    run:
        markers = pd.read_csv(input.txt, sep="\t")
        markers = markers.rename(columns={"Microhaplotype ID": "Name", "rs_ID": "VarRef"})
        markers["NumVars"] = markers["VarRef"].apply(lambda x: x.count(";") + 1)
        markers["NumVarsPos"] = markers["Position"].apply(lambda x: x.count(";") + 1)
        markers["Consistent"] = markers["NumVars"] == markers["NumVarsPos"]
        inconsistent = markers[markers.Consistent == False]
        assert len(inconsistent) == 0
        markers["Xref"] = None
        markers["Refr"] = None
        markers["Positions"] = None
        substitutions = {
            "mh06WL-066": "mh06WL-066b",
            "mh06WL-067": "mh06WL-067b",
            "mh06WL-068": "mh06WL-068b",
            "mh20WL-015": "mh20WL-001",
        }
        markers = markers.replace(substitutions)
        markers["Chrom"] = markers["Name"].apply(chrom_from_marker_name)
        markers = markers[["Name", "Xref", "NumVars", "Refr", "Chrom", "Positions", "VarRef"]]
        markers.to_csv(output.csv, index=False)
