# -----------------------------------------------------------------------------
# Copyright (c) 2020, Battelle National Biodefense Institute.
#
# This file is part of MicroHapDB (http://github.com/bioforensics/microhapdb)
# and is licensed under the BSD license: see LICENSE.txt.
# -----------------------------------------------------------------------------

from utils import smartopen, marker_coords


rule all:
    input: 'marker.tsv'


rule supp_file_s1:
    input: 'original/mmc8.txt'
    output: 'supp-file-s1.tsv'
    shell: 'python text2table.py < {input} > {output}'


rule dbsnp_subset:
    input:
        markers='supp-file-s1.tsv',
        dbsnp=config['dbsnp38'],
        rsidx=config['dbsnp38'].replace('.vcf.gz', '.rsidx'),
    output: 'dbsnp-subset.vcf.gz'
    run:
        markers = pandas.read_csv(input.markers, sep='\t')
        rsids = list()
        for n, row in markers.iterrows():
            rsids.extend(row.RSIDs.split(','))
        rsids = ' '.join(rsids)
        command = f'rsidx search --header --out {output[0]} {input.dbsnp} {input.rsidx} {rsids}'
        shell(command)



rule marker_coords:
    input:
        script='./compile_marker_definitions.py'
        markers='supp-file-s1.tsv',
        dbsnp='dbsnp-subset.vcf.gz',
    output: 'marker.tsv'
    shell: '{input} {output}'
