# -----------------------------------------------------------------------------
# Copyright (c) 2019, Battelle National Biodefense Institute.
#
# This file is part of MicroHapDB (http://github.com/bioforensics/microhapdb)
# and is licensed under the BSD license: see LICENSE.txt.
# -----------------------------------------------------------------------------

import pandas

rule all:
    input: 'frequency.tsv', 'marker-informativeness.tsv', 'marker-fst.tsv'


rule markerrsids:
    input: 'get-marker-rsids.py'
    output: 'marker-rsids-MicroHapDB-0.5.tsv'
    shell: './get-marker-rsids.py > marker-rsids-MicroHapDB-0.5.tsv'


rule freqs:
    input:
        'mhfreqs.py',
        'sample-pops.tsv',
        'marker-rsids-MicroHapDB-0.5.tsv'
    output:
        'frequency.tsv'
    shell: './mhfreqs.py sample-pops.tsv marker-rsids-MicroHapDB-0.5.tsv > frequency.tsv'


rule informativeness:
    input:
        'prepinfocalc.py',
        'infocalc',
        'cleanup-in.py',
        'sample-pops.tsv',
        'marker-rsids-MicroHapDB-0.5.tsv'
    output:
        'marker-informativeness.tsv',
        'individual-haplotypes.txt'
    shell:
        '''
        ./prepinfocalc.py sample-pops.tsv marker-rsids-MicroHapDB-0.5.tsv > individual-haplotypes.txt
        ./infocalc -column 2 -numpops 26 -input individual-haplotypes.txt -output marker-informativeness.txt
        ./cleanup-in.py < marker-informativeness.txt > marker-informativeness.tsv
        '''


rule fst:
    input:
        'fstcalc.py',
        'individual-haplotypes.txt'
    output:
        'marker-fst.tsv'
    shell: './fstcalc.py individual-haplotypes.txt > marker-fst.tsv'
